#!/usr/bin/env node
//
// setup-env.mjs — generate every services/<name>/.env from ONE root .env.
//
// Why this exists: the platform has 15 services that all talk to the same
// database and the same Supabase project. Before this script each engineer
// hand-maintained 15 copies of the same connection string, and they drifted:
// `booking-service` had PORT=4017 while the canonical port is 4005, only
// `template-service` carried the pgbouncer flags the transaction pooler needs,
// and DIRECT_DATABASE_URL was referenced by every schema.prisma but defined
// nowhere. One file to edit, one command to run, no drift.
//
// Usage:
//   node scripts/setup-env.mjs            # generate (refuses to clobber edits)
//   node scripts/setup-env.mjs --force    # overwrite generated files
//   node scripts/setup-env.mjs --check    # verify only, non-zero on problems
//
// Secrets are never printed — output reports key names and shapes only.

import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const args = new Set(process.argv.slice(2))
const FORCE = args.has('--force')
const CHECK = args.has('--check')

const GENERATED_MARKER = '# GENERATED by `npm run setup:env` — DO NOT EDIT.'

// ── Canonical service registry ───────────────────────────────────────────────
// Ports come from run-all.sh so there is exactly one place they are declared.
function readPortTable() {
  const sh = fs.readFileSync(path.join(ROOT, 'scripts', 'run-all.sh'), 'utf8')
  const m = sh.match(/^SERVICES="([^"]+)"/m)
  if (!m) throw new Error('Could not find SERVICES=... in scripts/run-all.sh')
  const table = {}
  for (const pair of m[1].trim().split(/\s+/)) {
    const [name, port] = pair.split(':')
    table[name] = Number(port)
  }
  return table
}

// Services granted the Supabase service-role key. It bypasses row-level
// security, so this is an allowlist, not a default — do not add a service
// without a code reference to justify it.
//
// venue-service is the only consumer: venues.controller.ts and
// organisations.controller.ts. comms-service was on this list historically but
// has no reference to the key anywhere in src/, so it no longer receives it.
const SERVICE_ROLE_KEY_ALLOWLIST = new Set(['venue'])

// Keys only one or two services consume. They are propagated from the root .env
// when set, listed in that service's .env.example, and reported by --check when
// missing so they cannot disappear from the record again.
//
// `productionRequired` keys fall back to a committed dev default inside the
// service (see services/integration-service/src/config/configuration.ts) — which
// means an unset value is silently insecure rather than a startup failure, so
// --check flags it.
const SERVICE_EXTRA_KEYS = {
  integration: [
    { key: 'API_KEY_HASH_SECRET', productionRequired: true },
    { key: 'TOKEN_ENCRYPTION_KEY', productionRequired: true },
    { key: 'OAUTH_STATE_SECRET', productionRequired: true },
  ],
  comms: [
    { key: 'RESEND_API_KEY' },
    { key: 'RESEND_FROM_ADDRESS' },
    { key: 'AZURE_COMMUNICATION_CONNECTION_STRING' },
    { key: 'AZURE_COMMUNICATION_SENDER_ADDRESS' },
    { key: 'AZURE_COMMUNICATION_PHONE_NUMBER' },
    { key: 'AZURE_SERVICE_BUS_CONNECTION_STRING' },
    { key: 'AZURE_SERVICE_BUS_TOPICS' },
  ],
  template: [{ key: 'REDIS_URL' }],
}

// Non-standard aliases some services use for a peer's URL.
const URL_ALIASES = { CUSTOMER_SERVICE_URL: 'people' }

// ── Root .env ────────────────────────────────────────────────────────────────
const REQUIRED_ROOT_KEYS = ['DATABASE_URL', 'SUPABASE_URL', 'INTERNAL_SECRET']
const OPTIONAL_ROOT_KEYS = [
  'SUPABASE_SERVICE_ROLE_KEY',
  'SUPABASE_JWT_SECRET',
  'CLUBSPARK_REGION',
  'REDIS_URL',
  'DATABASE_READ_URL',
  'ANTHROPIC_API_KEY',
  'DB_CONNECTION_LIMIT',
  'SUPABASE_ANON_KEY',
  'PUBLIC_BASE_DOMAIN',
  'NODE_ENV',
]

function parseEnv(text) {
  const out = {}
  for (const line of text.split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/)
    if (!m) continue
    let value = m[2].trim()
    const quoted = /^(["'])(.*)\1$/.exec(value)
    if (quoted) {
      value = quoted[2]
    } else {
      // Strip an unquoted trailing comment. Without this,
      // `DB_CONNECTION_LIMIT=5 # note` yields the value "5 # note", which then
      // lands verbatim in a connection string.
      value = value.replace(/\s+#.*$/, '').trim()
    }
    out[m[1]] = value
  }
  return out
}

function loadRoot() {
  const file = path.join(ROOT, '.env')
  if (!fs.existsSync(file)) {
    console.error('\n  No root .env found.\n')
    console.error('  Copy the template and fill in the real values:')
    console.error('      cp .env.example .env\n')
    console.error('  It needs: ' + REQUIRED_ROOT_KEYS.join(', ') + '\n')
    process.exit(1)
  }
  const env = parseEnv(fs.readFileSync(file, 'utf8'))
  const missing = REQUIRED_ROOT_KEYS.filter((k) => !env[k])
  if (missing.length) {
    console.error(`\n  Root .env is missing: ${missing.join(', ')}\n`)
    process.exit(1)
  }
  // NODE_ENV=test would disable InternalSecretGuard on every service (it returns
  // true outright in that mode), leaving the internal cross-tenant write routes
  // unauthenticated. Never let it reach a generated file.
  if (env.NODE_ENV && !['development', 'production'].includes(env.NODE_ENV)) {
    console.error(
      `\n  Root .env sets NODE_ENV=${env.NODE_ENV}. Only 'development' or 'production' are allowed here.` +
        `\n  NODE_ENV=test disables InternalSecretGuard, which is the only authenticator on the` +
        `\n  internal reassign-customer and events/inbound routes. The test harnesses set it themselves.\n`,
    )
    process.exit(1)
  }
  // The root file holds the database password and INTERNAL_SECRET; `cp` from the
  // tracked example inherits 0644.
  if ((fs.statSync(file).mode & 0o077) !== 0) {
    fs.chmodSync(file, 0o600)
    console.log('  note: tightened root .env to 0600')
  }
  return env
}

// ── Connection strings ───────────────────────────────────────────────────────
// The generator does NOT append pgbouncer/connection_limit flags.
//
// PrismaService already appends `pgbouncer=true&connection_limit=N&pool_timeout=10`
// in all 15 services, and every test/helpers/db.ts appends its own. A third set
// here produced a doubled query string, e.g.
//   ?pgbouncer=true&connection_limit=5?pgbouncer=true&connection_limit=1&pool_timeout=10
// which Prisma 5.22 accepts while the LAST duplicate wins — so anything written
// here was silently ignored, and a future Prisma version would reject it outright.
//
// One owner: PrismaService. It reads DB_CONNECTION_LIMIT (default 1), which this
// script propagates, so the knob lives in the root .env and applies exactly once.
//
// The credential is passed through untouched. Parsing it with `new URL()` and
// re-serialising corrupts any password containing `#` or `?`, splicing query
// params into the middle of the credential.
function runtimeUrl(base) {
  const lastAt = base.lastIndexOf('@')
  const credentials = lastAt === -1 ? '' : base.slice(0, lastAt)
  if (/[?#]/.test(credentials)) {
    throw new Error(
      'DATABASE_URL credentials contain a raw ? or # — percent-encode them (%3F / %23)',
    )
  }
  return base
}

// DIRECT_DATABASE_URL is deliberately NOT generated.
//
// Nothing at runtime reads it — Prisma Client connects via `url`; `directUrl` is
// used only by the Prisma CLI. Both sanctioned migration paths
// (scripts/migrate-all.sh, scripts/check-migration-drift.sh) derive it
// themselves, per service, including the ?schema= pin. Leaving it undefined means
// an ad-hoc `npx prisma migrate deploy` inside a service directory fails fast
// with P1012 instead of running — and that is the desired outcome, because the
// ad-hoc path skips the shared bootstrap SQL and the multi-pass ordering that
// exists for cross-schema function dependencies. Use `npm run migrate:all`.

// Keys an override may never set. `.env.override` is the lowest-trust input in
// the system — git-ignored, per-machine, unreviewed — so it must not be able to
// weaken a security control:
//
//   NODE_ENV                  — InternalSecretGuard returns true outright when
//                               NODE_ENV==='test', and it reads process.env per
//                               request. That guard is the SOLE authenticator on
//                               the internal reassign-customer and events/inbound
//                               routes, which take the tenant from a header.
//   INTERNAL_SECRET           — the service-to-service authenticator.
//   SUPABASE_SERVICE_ROLE_KEY — bypasses row-level security; allowlisted above.
//   DIRECT_DATABASE_URL       — deliberately unset so ad-hoc prisma migrate
//                               fails fast rather than skipping migrate-all.sh.
const OVERRIDE_DENYLIST = new Set([
  'NODE_ENV',
  'INTERNAL_SECRET',
  'SUPABASE_SERVICE_ROLE_KEY',
  'DIRECT_DATABASE_URL',
])

// ── Portals ──────────────────────────────────────────────────────────────────
// The three Next.js apps are generated too. They were previously outside this
// script, which is how internal-portal's INTERNAL_SECRET came to drift from the
// services' — and admin-service's guard is fail-closed, so the symptom was every
// internal admin call 401ing with no explanation.
//
// `peers` maps the env var name to a service in the port table; some use a
// different name for the same service (FACILITY -> venue, CUSTOMER -> people).
const PORTALS = {
  'admin-portal': {
    file: '.env.local',
    publicSupabase: true,
    anthropic: true,
    peers: {
      NEXT_PUBLIC_BOOKING_SERVICE_URL: 'booking',
      NEXT_PUBLIC_FACILITY_SERVICE_URL: 'venue',
      NEXT_PUBLIC_PEOPLE_SERVICE_URL: 'people',
      NEXT_PUBLIC_MEMBERSHIP_SERVICE_URL: 'membership',
      NEXT_PUBLIC_ADMIN_SERVICE_URL: 'admin',
      NEXT_PUBLIC_COACHING_SERVICE_URL: 'coaching',
      NEXT_PUBLIC_TEAM_SERVICE_URL: 'team',
      NEXT_PUBLIC_PAYMENT_SERVICE_URL: 'payment',
      NEXT_PUBLIC_INTEGRATION_SERVICE_URL: 'integration',
      ENTITLEMENT_SERVICE_URL: 'entitlement',
    },
  },
  'customer-portal': {
    file: '.env.local',
    publicSupabase: true,
    anthropic: true,
    baseDomain: true,
    peers: {
      NEXT_PUBLIC_VENUE_SERVICE_URL: 'venue',
      NEXT_PUBLIC_BOOKING_SERVICE_URL: 'booking',
      NEXT_PUBLIC_CUSTOMER_SERVICE_URL: 'people',
      NEXT_PUBLIC_MEMBERSHIP_SERVICE_URL: 'membership',
      NEXT_PUBLIC_COACHING_SERVICE_URL: 'coaching',
      NEXT_PUBLIC_COMPETITION_SERVICE_URL: 'competition',
      NEXT_PUBLIC_TEAM_SERVICE_URL: 'team',
    },
  },
  'internal-portal': {
    file: '.env.local',
    publicSupabase: true,
    // Staff-only portal: it needs the same INTERNAL_SECRET the services use, which
    // is the whole reason it belongs in this script.
    internalSecret: true,
    peers: { ADMIN_SERVICE_URL: 'admin' },
  },
}

function portalEnv(name, spec, root, portTable) {
  const lines = []
  lines.push(GENERATED_MARKER)
  lines.push('# Edit the root .env and re-run `npm run setup:env`.')
  lines.push('')
  if (spec.publicSupabase) {
    lines.push(`NEXT_PUBLIC_SUPABASE_URL=${root.SUPABASE_URL}`)
    if (!root.SUPABASE_ANON_KEY) {
      throw new Error(`${name} needs SUPABASE_ANON_KEY but the root .env does not define it`)
    }
    lines.push(`NEXT_PUBLIC_SUPABASE_ANON_KEY=${root.SUPABASE_ANON_KEY}`)
  }
  if (spec.internalSecret) {
    lines.push('')
    lines.push('# Must match the services byte-for-byte; the guard is fail-closed.')
    lines.push(`INTERNAL_SECRET=${root.INTERNAL_SECRET}`)
  }
  if (spec.anthropic && root.ANTHROPIC_API_KEY) {
    lines.push(`ANTHROPIC_API_KEY=${root.ANTHROPIC_API_KEY}`)
  }
  if (spec.baseDomain && root.PUBLIC_BASE_DOMAIN) {
    lines.push(`NEXT_PUBLIC_BASE_DOMAIN=${root.PUBLIC_BASE_DOMAIN}`)
  }
  lines.push('')
  lines.push('# Service URLs — derived from the port table in scripts/run-all.sh.')
  for (const [key, peer] of Object.entries(spec.peers)) {
    const port = portTable[peer]
    if (!port) throw new Error(`${name}: no port for peer '${peer}'`)
    lines.push(`${key}=http://127.0.0.1:${port}`)
  }
  lines.push('')
  return lines.join('\n')
}

// Values a single service must differ on live in services/<name>/.env.override
// (git-ignored). They are merged in here, at generation time, so nothing in the
// 15 services' startup code has to know about a second file.
function readOverride(dir) {
  const file = path.join(dir, '.env.override')
  if (!fs.existsSync(file)) return null
  const parsed = parseEnv(fs.readFileSync(file, 'utf8'))
  const blocked = Object.keys(parsed).filter((k) => OVERRIDE_DENYLIST.has(k))
  if (blocked.length) {
    throw new Error(`.env.override may not set ${blocked.join(', ')} (security-relevant)`)
  }
  return Object.keys(parsed).length ? parsed : null
}

function applyOverride(body, override) {
  if (!override) return body
  const lines = body.split('\n')
  const remaining = { ...override }
  const out = lines.map((line) => {
    const m = line.match(/^([A-Z0-9_]+)=/)
    if (m && Object.prototype.hasOwnProperty.call(remaining, m[1])) {
      const v = remaining[m[1]]
      delete remaining[m[1]]
      return `${m[1]}=${v}`
    }
    return line
  })
  const added = Object.entries(remaining)
  if (added.length) {
    out.push('# Added by .env.override')
    for (const [k, v] of added) out.push(`${k}=${v}`)
    out.push('')
  }
  return out.join('\n')
}

function serviceEnv(name, port, root, portTable) {
  const lines = []
  lines.push(GENERATED_MARKER)
  lines.push('# Edit the root .env and re-run `npm run setup:env`.')
  lines.push('# Service-specific values that must differ: put them in .env.override')
  lines.push('# (same directory, git-ignored) — setup:env merges them in here.')
  lines.push('')
  lines.push(`PORT=${port}`)
  lines.push(`NODE_ENV=${root.NODE_ENV || 'development'}`)
  lines.push('')
  lines.push('# Database. Pooler flags (pgbouncer, connection_limit, pool_timeout) are')
  lines.push('# applied once, by PrismaService, from DB_CONNECTION_LIMIT below.')
  lines.push(`DATABASE_URL=${runtimeUrl(root.DATABASE_URL)}`)
  lines.push(`DB_CONNECTION_LIMIT=${root.DB_CONNECTION_LIMIT || '1'}`)
  if (root.DATABASE_READ_URL) lines.push(`DATABASE_READ_URL=${root.DATABASE_READ_URL}`)
  lines.push('')
  lines.push('# Auth / platform')
  lines.push(`SUPABASE_URL=${root.SUPABASE_URL}`)
  if (root.SUPABASE_JWT_SECRET) lines.push(`SUPABASE_JWT_SECRET=${root.SUPABASE_JWT_SECRET}`)
  if (SERVICE_ROLE_KEY_ALLOWLIST.has(name)) {
    if (!root.SUPABASE_SERVICE_ROLE_KEY) {
      throw new Error(
        `${name}-service needs SUPABASE_SERVICE_ROLE_KEY but the root .env does not define it`,
      )
    }
    lines.push(`SUPABASE_SERVICE_ROLE_KEY=${root.SUPABASE_SERVICE_ROLE_KEY}`)
  }
  lines.push(`INTERNAL_SECRET=${root.INTERNAL_SECRET}`)
  if (root.CLUBSPARK_REGION) lines.push(`CLUBSPARK_REGION=${root.CLUBSPARK_REGION}`)
  if (root.ANTHROPIC_API_KEY) lines.push(`ANTHROPIC_API_KEY=${root.ANTHROPIC_API_KEY}`)
  const extras = SERVICE_EXTRA_KEYS[name] || []
  if (extras.length) {
    lines.push('')
    lines.push(`# Keys only ${name}-service uses. Set them in the root .env.`)
    for (const { key } of extras) if (root[key]) lines.push(`${key}=${root[key]}`)
  }
  lines.push('')
  lines.push('# Peer services — derived from the port table in scripts/run-all.sh.')
  for (const [peer, peerPort] of Object.entries(portTable)) {
    if (peer === name) continue
    lines.push(`${peer.toUpperCase()}_SERVICE_URL=http://127.0.0.1:${peerPort}`)
  }
  for (const [alias, target] of Object.entries(URL_ALIASES)) {
    if (target === name) continue
    lines.push(`${alias}=http://127.0.0.1:${portTable[target]}`)
  }
  lines.push('')
  return lines.join('\n')
}

// ── Main ─────────────────────────────────────────────────────────────────────
const portTable = readPortTable()
const root = loadRoot()

const EXTRA_KEY_NAMES = Object.values(SERVICE_EXTRA_KEYS)
  .flat()
  .map((e) => e.key)
const unknown = Object.keys(root).filter(
  (k) => ![...REQUIRED_ROOT_KEYS, ...OPTIONAL_ROOT_KEYS, ...EXTRA_KEY_NAMES].includes(k),
)

const rows = []
let wrote = 0
let problems = 0

for (const [name, port] of Object.entries(portTable)) {
  const dir = path.join(ROOT, 'services', `${name}-service`)
  if (!fs.existsSync(dir)) {
    rows.push([name, 'no service directory', 'SKIP'])
    continue
  }
  const file = path.join(dir, '.env')
  let content
  let override
  try {
    override = readOverride(dir)
    content = applyOverride(serviceEnv(name, port, root, portTable), override)
  } catch (e) {
    rows.push([name, e.message, 'FAIL'])
    problems++
    continue
  }
  const note = override ? ` +override(${Object.keys(override).length})` : ''

  const exists = fs.existsSync(file)
  const current = exists ? fs.readFileSync(file, 'utf8') : ''
  const isGenerated = current.startsWith(GENERATED_MARKER)

  if (CHECK) {
    // Mode is checked, not assumed: writeFileSync's `mode` only applies when it
    // creates the file, so a pre-existing 0644 stays 0644 on a rewrite.
    const loose = exists && (fs.statSync(file).mode & 0o077) !== 0
    if (!exists) {
      rows.push([name, 'missing .env', 'FAIL'])
      problems++
    } else if (loose) {
      rows.push([name, 'world/group-readable — re-run setup:env', 'FAIL'])
      problems++
    } else if (!isGenerated) {
      rows.push([name, 'hand-edited (not generated)', 'WARN'])
    } else if (current !== content) {
      rows.push([name, 'stale — re-run setup:env', 'FAIL'])
      problems++
    } else {
      // Flag production-required secrets that fall back to a committed dev
      // default inside the service — unset is silently insecure, not a failure.
      const weak = (SERVICE_EXTRA_KEYS[name] || [])
        .filter((e) => e.productionRequired && !root[e.key])
        .map((e) => e.key)
      if (weak.length) rows.push([name, `using dev defaults for ${weak.join(', ')}`, 'WARN'])
      else rows.push([name, `port ${port}${note}`, 'ok'])
    }
    continue
  }

  if (exists && !isGenerated && !FORCE) {
    rows.push([name, 'hand-edited — refusing to clobber (use --force)', 'SKIP'])
    problems++
    continue
  }

  // Always chmod, never rely on writeFileSync's mode: it is honoured only on
  // create, so a rewrite would silently leave the previous (often 0644) mode on
  // a file holding the database password, INTERNAL_SECRET and possibly the
  // RLS-bypassing service-role key.
  const modeWasLoose = exists && (fs.statSync(file).mode & 0o077) !== 0
  if (current === content && !modeWasLoose) {
    rows.push([name, `port ${port}${note}`, 'unchanged'])
    continue
  }
  fs.writeFileSync(file, content)
  fs.chmodSync(file, 0o600)
  wrote++
  rows.push([name, `port ${port}${note}`, exists ? 'rewritten' : 'created'])
}

// ── Portals (generation) ──────────────────────────────────────────────────
for (const [name, spec] of Object.entries(PORTALS)) {
  const dir = path.join(ROOT, name)
  if (!fs.existsSync(dir)) {
    rows.push([name, 'no directory', 'SKIP'])
    continue
  }
  const file = path.join(dir, spec.file)
  let content
  try {
    content = portalEnv(name, spec, root, portTable)
  } catch (e) {
    rows.push([name, e.message, 'FAIL'])
    problems++
    continue
  }
  const exists = fs.existsSync(file)
  const current = exists ? fs.readFileSync(file, 'utf8') : ''
  const isGenerated = current.startsWith(GENERATED_MARKER)
  const loose = exists && (fs.statSync(file).mode & 0o077) !== 0

  if (CHECK) {
    if (!exists) {
      rows.push([name, 'missing ' + spec.file, 'FAIL'])
      problems++
    } else if (loose) {
      rows.push([name, 'world/group-readable — re-run setup:env', 'FAIL'])
      problems++
    } else if (!isGenerated) {
      rows.push([name, 'hand-edited, not generated', 'WARN'])
    } else if (current !== content) {
      rows.push([name, 'stale — re-run setup:env', 'FAIL'])
      problems++
    } else {
      rows.push([name, spec.file, 'ok'])
    }
    continue
  }

  if (exists && !isGenerated && !FORCE) {
    rows.push([name, 'hand-edited — refusing to clobber, use --force', 'SKIP'])
    problems++
    continue
  }
  if (current === content && !loose) {
    rows.push([name, spec.file, 'unchanged'])
    continue
  }
  fs.writeFileSync(file, content)
  fs.chmodSync(file, 0o600)
  wrote++
  rows.push([name, spec.file, exists ? 'rewritten' : 'created'])
}

const w = Math.max(...rows.map((r) => r[0].length))
for (const [a, b, c] of rows) console.log(`  ${a.padEnd(w)}  ${c.padEnd(10)} ${b}`)

if (unknown.length) {
  console.log(`\n  note: root .env has keys this script does not propagate: ${unknown.join(', ')}`)
}

if (CHECK) {
  console.log(
    `\n  ${problems === 0 ? 'env OK' : `${problems} problem(s)`} across ${rows.length} services`,
  )
  process.exit(problems === 0 ? 0 : 1)
}
console.log(`\n  wrote ${wrote} of ${rows.length} service env files (mode 0600)`)
console.log('  DIRECT_DATABASE_URL is intentionally not set — use `npm run migrate:all`.')
// Exit non-zero on any FAIL/SKIP in generate mode too. Previously only --check
// consulted `problems`, so `npm run setup:env && npm run start:services` would
// carry on after leaving a service with no .env, or a drifted hand-edited one.
if (problems > 0) {
  console.error(
    `\n  ${problems} service(s) not generated — see above. Nothing downstream should run.`,
  )
  process.exit(1)
}
